name: Gentoo Overlay QA

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Cache Portage data
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/distfiles
            /var/db/repos/gentoo
            /var/cache/binpkgs
            /var/tmp/portage
          key: gentoo-portage-${{ runner.os }}-${{ hashFiles('**/ci.yml') }}-${{ github.run_id }}
          restore-keys: |
            gentoo-portage-${{ runner.os }}-${{ hashFiles('**/ci.yml') }}-
            gentoo-portage-${{ runner.os }}-

      - name: Update Portage
        run: |
          emerge-webrsync

      - name: Install QA tools
        run: |
          # Install QA tools (will use cached build artifacts if available)
          emerge -q dev-util/pkgcheck dev-util/pkgdev

      - name: Run pkgcheck
        run: |
          # Run pkgcheck but only report, don't fail
          pkgcheck scan --net || true

          echo ""
          echo "QA check completed. Review warnings above."
          echo "To see only errors: pkgcheck scan --exit error"
