name: Gentoo Overlay QA

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Update Portage
        run: |
          emerge-webrsync

      - name: Install QA tools
        run: emerge -q dev-util/pkgcheck dev-util/pkgdev

      - name: Run pkgcheck
        run: |
          # Run pkgcheck but only report, don't fail
          pkgcheck scan --net || true

          echo ""
          echo "QA check completed. Review warnings above."
          echo "To see only errors: pkgcheck scan --exit error"
